blank_issues_enabled: false
contact_links:
  - name: CachyOS Forum
    url: https://discuss.cachyos.org
    about: General questions and community discussion
  - name: CachyOS Discord
    url: https://discord.gg/cachyos-862292009423470592
    about: Real-time chat and support
